spring:
  profiles:
    active: dev
  application:
    name: pharmacy
  datasource:
    url: jdbc:postgresql://localhost:5432/arise
    username: postgres
    password: password
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: classpath:application-secrets.yml
